"""empty message

Revision ID: 72ad555fb2dd
Revises: b8f878987a88
Create Date: 2022-10-31 23:54:56.013809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ad555fb2dd'
down_revision = 'b8f878987a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Favorites', ['id'])
    op.create_unique_constraint(None, 'People', ['id'])
    op.create_unique_constraint(None, 'Planets', ['id'])
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'Planets', type_='unique')
    op.drop_constraint(None, 'People', type_='unique')
    op.drop_constraint(None, 'Favorites', type_='unique')
    # ### end Alembic commands ###
